### ISSUE TITLE
ValueError: Expected the given number of height ratios to match the number of rows of the grid

### ISSUE THREAD

**Issue by pinkwerks** [blueberrymusic/DeepLearningBookCode-Volume2#1]
Trying to run `draw_four_ups(book_fig_sets, 'VGG-book')` I get:
ValueError: Expected the given number of height ratios to match the number of rows of the grid

https://github.com/blueberrymusic/DeepLearningBookCode-Volume2/blob/85d242e7a8897dc4049cdcc68af04edb7cadf024/Chapter20-DeepLearning/DeepLearning-Notebook.ipynb#L201

I found changing the above line from:
`gs = gridspec.GridSpec(2,4, height_ratios=[2,2,1,1,1,1,1,1])`
to:
`gs = gridspec.GridSpec(2,4, height_ratios=[2,2])`

allowed the example to run. Perhaps something changed in matplotlib that is less forgiving of extra items in the height ratios list?

**Comment by pinkwerks** [comment]
What is weird, is that it renders okay on github. I'm not sure why downloading and running it locally produces a difference.

**Comment by blueberrymusic** [comment]
Hi Pink!

I don’t know if replying to you directly works or not. Here’s hoping.

It sounds like matplotlib might have been updated in some way. Are you
using the latest release? It might also be some inconsistency between the
release for different platforms. I agree it’s a strange problem. I’ll try
to replicate the problem if I can, and then correct if (if I can!).

-Andrew

**Comment by pinkwerks** [comment]
Ahh - perhaps the github preview works because you've uploaded the pictures in the input_data folder already. In addition your notebook contains the output when you ran it. Github most likely doesn't run anycode, it's just displaying what's been uploaded.

**Comment by blueberrymusic** [comment]
Thanks - that makes a lot more sense. I was wondering how Github was
running Python code! It does show the notebook as I saved it, including the
output, but it doesn’t save the data behind those calculations. I left the
images in the notebooks so that it would be easier to see what’s making
what. Thank you for tracking down this issue, and the bad byte in the
Holmes database.

I’ve fixed the GridSpec line and merged your Holmes repair. Thank you for
taking the time to share these with me!

-Andrew
